<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>MailSpy</RootNamespace>
    <AssemblyName>MailSpy</AssemblyName>
    <StartupObject>MailSpy.App</StartupObject>
    <ApplicationIcon>mailspy.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework\Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="mailspy.png" />
    <Resource Include="mailspy.ico" />
    <Content Include="Scripts\*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="CopyToCommandr" AfterTargets="Build">
    <Exec Command="xcopy /E /Y /I /Q &quot;$(ProjectDir)$(OutDir)*&quot; &quot;$(ProjectDir)..\Commandr\$(OutDir)MailSpy\&quot;" />
  </Target>

</Project>
